<?php
// +----------------------------------------------------------------------
// | [RhaPHP System] Copyright (c) 2017-2020 http://www.rhaphp.com/
// +----------------------------------------------------------------------
// | [RhaPHP] 并不是自由软件,你可免费使用,未经许可不能去掉RhaPHP相关版权
// +----------------------------------------------------------------------
// | Author: Geeson <qimengkeji@vip.qq.com>
// +----------------------------------------------------------------------

namespace app\admin\controller;


use think\facade\Cookie;
use think\facade\Request;

class Appstore extends Base
{
    public $user = [];
    public $token = '';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (!empty($user = Cookie::get('official_user'))) {
            $this->user = $user;
            $this->token = $user['token'];
        }
        $this->assign('user', $this->user);
    }

    public function register()
    {
        $this->assign('domain', Request::domain());
        return view();
    }

    public function login()
    {
        if (Request::isPost()) {
            $data = input('post.');
            $url = "https://service.rhaphp.com/account/login";
            $result = httpPost($url, $data);
            if ($result == false) return json(['errcode' => -1, 'errmsg' => '系统繁忙，请稍后再试']);
            $result = json_decode($result, true);
            if (is_array($result) && !empty($result)) {
                if ($result['errcode'] != 0) {
                    return json($result);
                }
                $_C = $result;
                unset($_C['errmsg']);
                Cookie::forever('official_user', $_C);
                return json($result);
            }
        } else {

            return view();
        }
    }

    public function index()
    {
        return view();
    }

}